import * as assert from 'assert';

import { flashMapSize, formatBytes, formatRun, parseFlashMap } from '../../providers/flashMap';

// As `libxr gen` writes it for an STM32F407IG (DevC).
const F407 = `#pragma once
// Generated by \`libxr gen\`; do not edit by hand.
// MCU: STM32F407IGH6

#include "main.h"

#include "stm32_flash.hpp"

constexpr LibXR::FlashRegion FLASH_REGIONS[] = {
  {0x08000000, 0x00004000, 4},
  {0x08010000, 0x00010000, 1},
  {0x08020000, 0x00020000, 7},
};

constexpr size_t FLASH_REGION_NUMBER = sizeof(FLASH_REGIONS) / sizeof(LibXR::FlashRegion);
`;

suite('flash_map.hpp', () => {
	test('the MCU and every run of equal sectors are read', () => {
		const map = parseFlashMap(F407);
		assert.ok(map);
		assert.strictEqual(map.mcu, 'STM32F407IGH6');
		assert.deepStrictEqual(map.runs, [
			{ address: 0x08000000, sectorSize: 0x4000, sectorCount: 4 },
			{ address: 0x08010000, sectorSize: 0x10000, sectorCount: 1 },
			{ address: 0x08020000, sectorSize: 0x20000, sectorCount: 7 },
		]);
		assert.strictEqual(formatBytes(flashMapSize(map)), '1 MB');
		assert.deepStrictEqual(map.runs.map(formatRun), [
			'0x08000000: 16 KB x 4',
			'0x08010000: 64 KB x 1',
			'0x08020000: 128 KB x 7',
		]);
	});

	test('CRLF line ends, unsigned suffixes and a missing MCU comment are accepted', () => {
		const text = 'constexpr LibXR::FlashRegion FLASH_REGIONS[] = {\r\n  {0x08000000u, 2048u, 64u},\r\n};\r\n';
		const map = parseFlashMap(text);
		assert.ok(map);
		assert.strictEqual(map.mcu, undefined);
		assert.deepStrictEqual(map.runs, [{ address: 0x08000000, sectorSize: 2048, sectorCount: 64 }]);
		assert.strictEqual(formatRun(map.runs[0]), '0x08000000: 2 KB x 64');
		assert.strictEqual(formatBytes(flashMapSize(map)), '128 KB');
	});

	test('a file without FLASH_REGIONS gives no map', () => {
		assert.strictEqual(parseFlashMap('#pragma once\n// MCU: STM32F103C8T6\n'), undefined);
	});
});
